### ISSUE TITLE
[Question] I had a question about usage

### ISSUE THREAD

**Issue by MostHated** [JustInvoke/ConvexColliderCreator#1]
Hey there,
    Thanks for releasing this. You did a great job on the overall controls and everything. 👍  I checked the different sections of your video, but didn't see if there was a way to "best guess" and overall initial base collider automatically? I see that you can select and object and hit generate, and with the options available it made it sound like it might be able to auto-generate a collider for the selected object, then you could edit it with the handles and such after the fact. It looks like that is not actually the case?

Thanks,
-MH

**Comment by JustInvoke** [comment]
Sorry but the generate button just creates a collider based on the way the handles and parameters are set. There isn't a feature where it automatically adjusts the collider shape based on the object/mesh.

**Comment by MostHated** [comment]
No worries, I just wanted to make sure I wasn't missing something. Great package either way.
